import "./globals.css";
export const metadata = {
  title: "Vijaybhaskar Blogs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className='bg-[#f1eee5]'
      >
        {children}
      </body>
    </html>
  );
}
